# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chat.proto for package 'chat'

require 'grpc'
require 'chat_pb'

module Chat
  module ChatService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chat.ChatService'

      rpc :Chat, stream(::Chat::ChatMessage), stream(::Chat::ChatMessage)
    end

    Stub = Service.rpc_stub_class
  end
end
